# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Inhales"
description: > # this means to ignore newlines until "email:"
   Captured breath from the Digital World

url: http://inhal.es

email: tim.klapdor@gmail.com
#blog logo
logo: "/assets/images/inhale-logo.png"
# blog cover
cover: "/assets/images/inhale-1.jpg"

name: 'Tim Klapdor'
author: 'Tim Klapdor'
author_image: "/assets/images/closeup-240.jpg"

paginate: 20

# social icons and sharing options
social:
  - icon: twitter
    url: https://twitter.com/timklapdor
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon: facebook
#    url: https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon: github
    url: https://github.com/timklapdor
    desc: Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon: google-plus
#    url: https://google.com/???
#    desc: Add me on google+
#    share_url:
#    share_title:
#    share_link:

  - icon: rss
    url: http://inhal.es/feed.xml
    desc: Subscribe
    share_url:
    share_title:
    share_link:
    
  - icon: envelope
    url: mailto:tim.klapdor@gmail.com
    desc: Email
    share_url:
    share_title:
    share_link:
